name: Deploy to Preview Channel

on:
    pull_request:

jobs:
    build_and_preview:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - uses: actions/setup-node@v2
              with:
                  node-version: '12'
            - run: yarn setup staging atb
            - run: yarn install
            - run: yarn build
              env:
                  WEBSHOP_BASE_URL: ${{ secrets.BASE_URL_STAGING }}
                  WEBSHOP_FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG_STAGING }}
                  WEBSHOP_ORG_ID: atb
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: '${{ secrets.GITHUB_TOKEN }}'
                  firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STAGING }}'
                  expires: 2d
                  projectId: atb-mobility-platform-staging
                  target: webshop
