name: Deploy to Staging Channel

on:
    push:
        branches:
            - master

jobs:
    deploy_live_website:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - uses: actions/setup-node@v2
              with:
                  node-version: '12'
            - run: yarn install
            - run: yarn build
              env:
                  WEBSHOP_BASE_URL: ${{ secrets.BASE_URL_STAGING }}
                  WEBSHOP_FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG_STAGING }}
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: '${{ secrets.GITHUB_TOKEN }}'
                  firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STAGING }}'
                  projectId: atb-mobility-platform-staging
                  channelId: live
