name: E2E-tests of webshop

on:
  schedule:
    - cron:  '0 7,12,23 * * *'
  workflow_dispatch:
    inputs:
      videoRecording:
        description: 'Record video of the tests'
        required: true
        default: 'false'
      ticketPurchase:
        description: 'Include ticket purchase'     
        required: true
        default: 'false'
      branch:
        description: 'Define branch to test'     
        required: true
        default: 'master'

jobs:
  e2e-test:
    name: E2E-test
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        env:
          DEFAULT_VIDEO: 'false'
          DEFAULT_TICKET_PURCHASE: 'false'
          DEFAULT_BRANCH: 'master'
        run: |
          echo "INPUT_VIDEO=${{ github.event.inputs.videoRecording || env.DEFAULT_VIDEO }}" >> $GITHUB_ENV
          echo "INPUT_TICKET_PURCHASE=${{ github.event.inputs.ticketPurchase || env.DEFAULT_TICKET_PURCHASE }}" >> $GITHUB_ENV
          echo "INPUT_BRANCH=${{ github.event.inputs.branch || env.DEFAULT_BRANCH }}" >> $GITHUB_ENV
      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.INPUT_BRANCH }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # https://github.com/marketplace/actions/cypress-io
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        #env:
        #  CYPRESS_baseUrl: api.dev.local
        with:
          #config: video=${{ env.INPUT_VIDEO }}
          command: yarn cypress:run:report --config video=${{ env.INPUT_VIDEO }} --env withBuyTicket=${{ env.INPUT_TICKET_PURCHASE }}
          working-directory: e2e-tests

      - name: Create HTML report
        if: always()
        run: yarn cypress:html-testreport
        working-directory: ./e2e-tests

      - name: Upload test report html
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results-html
          path: |
            ./e2e-tests/cypress/results/assets
            ./e2e-tests/cypress/results/cypressTestReport.html
          retention-days: 3
          
      - name: Upload test report json
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results-json
          path: ./e2e-tests/cypress/results/cypressTestReport.json
          retention-days: 3
          
      - name: Upload video recording
        if: contains(env.INPUT_VIDEO, 'true')
        uses: actions/upload-artifact@v2
        with:
          name: video-recording
          path: ./e2e-tests/cypress/videos
          if-no-files-found: ignore
          retention-days: 3
            
