name: E2E-tests of webshop

on:
  workflow_dispatch:

jobs:
  e2e-test:
    name: E2E-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: tor/e2e-tester
          
      - name: Install Cypress
        run: npm install
        working-directory: ./e2e-tests
        
      - name: Run Cypress test
        run: ./node_modules/.bin/cypress run --reporter mocha-multi-reporters --reporter-options configFile=cypress-reporter-config.json 
        working-directory: ./e2e-tests
        continue-on-error: true
        
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: "E2E Test Results"
          files: ./e2e-tests/cypress/results/*.xml
          report_individual_runs: true
        
      - name: Merge results
        run: node cypress/scripts/combineTestReports.js 
        working-directory: ./e2e-tests
        
      - name: Create HTML report
        run: node_modules/.bin/marge cypress/results/cypressTestReport.json --code false --reportFilename cypressTestReport --reportDir ./cypress/results
        working-directory: ./e2e-tests
        
      - name: Upload test report html
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            ./e2e-tests/cypress/results/assets
            ./e2e-tests/cypress/results/cypressTestReport.html
          retention-days: 3
