name: E2E-tests Ubuntu Firefox

on:
  schedule:
    - cron:  '30 5 * * *'
  workflow_dispatch:
    inputs:
      testsToRun:
        description: 'Run all or only a specific test (*.e2e_spec.js)'
        required: true
        default: 'runAllTests'
      videoRecording:
        description: 'Record video of the tests if any failures'
        required: true
        default: 'false'
      ticketPurchase:
        description: 'Include ticket purchase'     
        required: true
        default: 'false'
      branch:
        description: 'Define branch to test'     
        required: true
        default: 'master'

jobs:
  e2e-test:
    name: E2E-test
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.17.0-chrome91-ff89
      options: --user 1001

    steps:
      - name: Set variables
        env:
          DEFAULT_VIDEO: 'false'
          DEFAULT_TICKET_PURCHASE: 'false'
          DEFAULT_BRANCH: 'master'
          DEFAULT_TEST: 'runAllTests'
        run: |
          echo "INPUT_VIDEO=${{ github.event.inputs.videoRecording || env.DEFAULT_VIDEO }}" >> $GITHUB_ENV
          echo "INPUT_TICKET_PURCHASE=${{ github.event.inputs.ticketPurchase || env.DEFAULT_TICKET_PURCHASE }}" >> $GITHUB_ENV
          echo "INPUT_BRANCH=${{ github.event.inputs.branch || env.DEFAULT_BRANCH }}" >> $GITHUB_ENV
          echo "INPUT_TEST=${{ github.event.inputs.testsToRun || env.DEFAULT_TEST }}" >> $GITHUB_ENV
      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.INPUT_BRANCH }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # https://github.com/marketplace/actions/cypress-io
      - name: Run all Cypress tests
        if: env.INPUT_TEST == 'runAllTests'
        uses: cypress-io/github-action@v2
        #env:
        #  CYPRESS_baseUrl: api.dev.local
        with:
          #config: video=${{ env.INPUT_VIDEO }}
          command: yarn cypress:run:report --config video=${{ env.INPUT_VIDEO }} --env runOnGitHub=true,withBuyTicket=${{ env.INPUT_TICKET_PURCHASE }} --browser firefox
          working-directory: e2e-tests

      - name: Run single Cypress test
        if: env.INPUT_TEST != 'runAllTests'
        uses: cypress-io/github-action@v2
        with:
          command: yarn cypress:run:report --config video=${{ env.INPUT_VIDEO }} --env runOnGitHub=true,withBuyTicket=${{ env.INPUT_TICKET_PURCHASE }} --browser firefox --spec cypress/integration/tests/${{ env.INPUT_TEST }}.e2e_spec.js
          working-directory: e2e-tests

      - name: Create HTML report
        if: always()
        run: yarn cypress:html-testreport
        working-directory: ./e2e-tests

      - name: Upload test report html
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results-html
          path: |
            ./e2e-tests/cypress/results/assets
            ./e2e-tests/cypress/results/cypressTestReport.html
          retention-days: 3
          
      - name: Upload test report json
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results-json
          path: ./e2e-tests/cypress/results/cypressTestReport.json
          retention-days: 3
          
      - name: Upload video recording
        if: failure() && contains(env.INPUT_VIDEO, 'true')
        uses: actions/upload-artifact@v2
        with:
          name: video-recording
          path: ./e2e-tests/cypress/videos
          if-no-files-found: ignore
          retention-days: 3
            
