name: E2E-tests of webshop

on:
  workflow_dispatch:

jobs:
  e2e-test:
    name: E2E-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: tor/e2e-tester
          
      - name: Install Cypress
        run: npm install
        working-directory: ./e2e-tests
        
      - name: Run Cypress test
        run: ./node_modules/.bin/cypress run --reporter mocha-multi-reporters --reporter-options configFile=cypress-reporter-config.json 
        working-directory: ./e2e-tests
        
      - name: Merge results
        run: node cypress/scripts/combineTestReports.js 
        working-directory: ./e2e-tests
        
      - name: Create HTML report
        run: node_modules/.bin/marge cypress/results/cypressTestReport.json --code false --reportFilename cypressTestReport --reportDir ./cypress/results
        working-directory: ./e2e-tests

      - name: Finish
        run: echo Finished
